name: Delivery experiment

on:
  push:
    branches:
      - v2
  pull_request_target:
    branches:
      - v2

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 12
          - x
    name: CI node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
      - run: yarn install
      - run: yarn ci

  delivery-experiment:
    name: Delivery experiment
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # yarn set version issue

      - uses: actions/setup-node@v2-beta
        with:
          check-latest: true

      - run: yarn install
      - run: yarn build

      - name: Set delivery info
        run: |
          echo "DELIVERY_VERSION=0.0.0-exp-${{ github.sha }}" >> $GITHUB_ENV
          echo "NPM_TAG=experimental" >> $GITHUB_ENV

      - run: echo "start delivery version ${{ env.DELIVERY_VERSION }}"

      # Delivery to NPM
      # - shell: pwsh
      #   env:
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: yarn config set npmAuthToken "$env:NPM_TOKEN"
      # - run: yarn delivery

      # Delivery to GPR
      - run: yarn config set npmPublishRegistry 'https://npm.pkg.github.com/'
      - run: yarn config set npmAuthToken "$env:GPR_TOKEN"
        shell: pwsh
        env:
          GPR_TOKEN: ${{ secrets.GPR_TOKEN }}

      - run: yarn delivery
